# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 17:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbe', '0003_auto_20150614_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='контент'),
        ),
    ]
