# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 17:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbe', '0008_auto_20170127_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='article content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='запись создана'),
        ),
    ]
