# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 17:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbe', '0009_auto_20170127_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(verbose_name='запись создана'),
        ),
    ]
