# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lbe', '0014_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='text',
            new_name='Text',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='published_date',
        ),
        migrations.AddField(
            model_name='chat',
            name='Author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
